### PR TITLE
--tables table1,table2 --ignore-tables table, table2

### PR DESCRIPTION
**Pull request by Themanwithoutaplan**
Added command line switches for limiting the dump to particular tables or excluding tables.

### CODE REVIEW

**Comment by ripienaar** [comment]
Nice, I'll merge

As a general rule its best to use && instead of and as && has a slightly higher precedence in ruby and would bring fewer surprises in odd situation.

Well done and thanks for this

**Comment by Themanwithoutaplan** [comment]
Am 20.05.2012, 20:01 Uhr, schrieb R.I.Pienaar  
reply@reply.github.com:

> Nice, I'll merge

Glad you like it.

> As a general rule its best to use && instead of and as && has a slightly  
> higher precedence in ruby and would bring fewer surprises in odd  
> situation.

Ugh! I'll try and remember that. To be honest it was a struggle enough to  
cope with Ruby's syntax for handling arguments, etc. Port to Python is  
next on my list, because at least I know how to write the tests!

> Well done and thanks for this

It has been all to scratch an itch of mine. New data is now available on  
httparchive.org so I can see how much faster things run if I only import  
the 2% of data I need!

**Comment by Themanwithoutaplan** [comment]
FWIW

$ gzip -d -c httparchive_May_15_2012.gz | ~/split-mysql-dump.rb -s -t pages
Found a new table: requests
`requests` not in list, ignoring
Found a new table: pages
    writing line: 74 53.981MB in 7 seconds 7.712MB/sec 

About 2 minutes in total instead of about 40

**Comment by ripienaar** [comment]
very very kewl

**Comment by Themanwithoutaplan** [comment]
Slight problem with data definitions it seems that some of the trailing sets cause problems because they are missing at the head

/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */
gives an error because the time zone is not set in the partial file.

Still, that should be fixable.

**Pull request merged**
